# Generated by Django 4.2.1 on 2023-06-08 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0006_supermarket_delete_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='supermarket',
            name='departments_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supermarket',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market', to=settings.AUTH_USER_MODEL),
        ),
    ]
